import html2canvas from 'html2canvas';
import jsPDF from 'jspdf';

const TAB_TITLES: Record<string, string> = {
  overview: 'Overview Dashboard',
  financial: 'Financial KPIs',
  tat: 'TAT Analysis',
  denial: 'Denial Analysis',
  ar: 'AR Management',
  payer: 'Payer Performance',
  leakage: 'Revenue Leakage',
  'ai-report': 'AI Report',
};

export async function exportTabToPDF(
  tabId: string,
  hospitalName: string,
  dateRange: string
) {
  const contentEl = document.getElementById('dashboard-tab-content');
  if (!contentEl) return;

  // Hide no-print elements inside the content area
  const noPrintEls = contentEl.querySelectorAll('.no-print');
  noPrintEls.forEach(el => (el as HTMLElement).style.display = 'none');

  const canvas = await html2canvas(contentEl, {
    scale: 2,
    useCORS: true,
    logging: false,
    backgroundColor: '#ffffff',
    windowWidth: 1440,
  });

  // Restore hidden elements
  noPrintEls.forEach(el => (el as HTMLElement).style.display = '');

  const imgData = canvas.toDataURL('image/jpeg', 0.92);
  const imgW = canvas.width;
  const imgH = canvas.height;

  const pdf = new jsPDF({
    orientation: imgW > imgH ? 'landscape' : 'portrait',
    unit: 'mm',
    format: 'a4',
  });

  const pageW = pdf.internal.pageSize.getWidth();
  const pageH = pdf.internal.pageSize.getHeight();
  const margin = 10;
  const headerH = 18;
  const usableW = pageW - margin * 2;
  const usableH = pageH - margin * 2 - headerH;

  const title = TAB_TITLES[tabId] || tabId;

  // Add header
  pdf.setFillColor(127, 29, 29); // rcm-900
  pdf.rect(0, 0, pageW, headerH + margin, 'F');
  pdf.setTextColor(255, 255, 255);
  pdf.setFontSize(14);
  pdf.setFont('helvetica', 'bold');
  pdf.text(`RCM Buddy — ${title}`, margin, margin + 6);
  pdf.setFontSize(8);
  pdf.setFont('helvetica', 'normal');
  pdf.text(`${hospitalName} · ${dateRange} · Generated ${new Date().toLocaleDateString('en-IN')}`, margin, margin + 12);

  // Scale image to fit page width
  const scale = usableW / (imgW / 2); // html2canvas scale=2
  const scaledH = (imgH / 2) * scale;
  const startY = headerH + margin + 2;

  if (scaledH <= usableH) {
    // Fits on one page
    pdf.addImage(imgData, 'JPEG', margin, startY, usableW, scaledH);
  } else {
    // Multi-page: slice the canvas
    const pxPerPage = Math.floor((usableH / scale) * 2); // in canvas pixels
    let srcY = 0;
    let pageNum = 0;

    while (srcY < imgH) {
      if (pageNum > 0) {
        pdf.addPage();
        // Repeat header
        pdf.setFillColor(127, 29, 29);
        pdf.rect(0, 0, pageW, headerH + margin, 'F');
        pdf.setTextColor(255, 255, 255);
        pdf.setFontSize(14);
        pdf.setFont('helvetica', 'bold');
        pdf.text(`RCM Buddy — ${title}`, margin, margin + 6);
        pdf.setFontSize(8);
        pdf.setFont('helvetica', 'normal');
        pdf.text(`${hospitalName} · Page ${pageNum + 1}`, margin, margin + 12);
      }

      const sliceH = Math.min(pxPerPage, imgH - srcY);
      const sliceCanvas = document.createElement('canvas');
      sliceCanvas.width = imgW;
      sliceCanvas.height = sliceH;
      const ctx = sliceCanvas.getContext('2d')!;
      ctx.drawImage(canvas, 0, srcY, imgW, sliceH, 0, 0, imgW, sliceH);

      const sliceData = sliceCanvas.toDataURL('image/jpeg', 0.92);
      const sliceScaledH = (sliceH / 2) * scale;
      pdf.addImage(sliceData, 'JPEG', margin, startY, usableW, sliceScaledH);

      srcY += pxPerPage;
      pageNum++;
    }
  }

  // Footer on last page
  pdf.setTextColor(150, 150, 150);
  pdf.setFontSize(7);
  pdf.text('Generated by RCM Buddy · rcmbuddy.com', margin, pageH - 5);

  pdf.save(`RCM_Buddy_${title.replace(/\s+/g, '_')}_${new Date().toISOString().slice(0, 10)}.pdf`);
}
