import html2canvas from 'html2canvas';
import jsPDF from 'jspdf';

const TAB_TITLES: Record<string, string> = {
  overview: 'Overview Dashboard',
  financial: 'Financial KPIs',
  tat: 'TAT Analysis',
  denial: 'Denial Analysis',
  ar: 'AR Management',
  payer: 'Payer Performance',
  leakage: 'Revenue Leakage',
  'ai-report': 'AI Report',
};

export async function exportTabToPDF(
  tabId: string,
  hospitalName: string,
  dateRange: string
) {
  const contentEl = document.getElementById('dashboard-tab-content');
  if (!contentEl) return;

  // Hide no-print elements inside the content area
  const noPrintEls = contentEl.querySelectorAll('.no-print');
  noPrintEls.forEach(el => (el as HTMLElement).style.display = 'none');

  // Force all recharts SVGs to render properly
  const svgs = contentEl.querySelectorAll('svg');
  svgs.forEach(svg => {
    svg.setAttribute('width', svg.getBoundingClientRect().width.toString());
    svg.setAttribute('height', svg.getBoundingClientRect().height.toString());
  });

  // Wait a tick for charts to be fully painted
  await new Promise(r => setTimeout(r, 300));

  const canvas = await html2canvas(contentEl, {
    scale: 2,
    useCORS: true,
    logging: false,
    backgroundColor: '#ffffff',
    windowWidth: 1440,
    scrollY: -window.scrollY,
    scrollX: 0,
    allowTaint: true,
    onclone: (clonedDoc) => {
      const clonedEl = clonedDoc.getElementById('dashboard-tab-content');
      if (clonedEl) {
        clonedEl.style.overflow = 'visible';
        clonedEl.style.height = 'auto';
        // Force SVGs in clone to be visible
        const clonedSvgs = clonedEl.querySelectorAll('.recharts-wrapper');
        clonedSvgs.forEach(wrapper => {
          (wrapper as HTMLElement).style.overflow = 'visible';
        });
      }
    }
  });

  // Restore hidden elements
  noPrintEls.forEach(el => (el as HTMLElement).style.display = '');

  const imgData = canvas.toDataURL('image/jpeg', 0.95);
  const imgW = canvas.width;
  const imgH = canvas.height;

  if (imgH < 10) return; // nothing captured

  const pdf = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4',
  });

  const pageW = pdf.internal.pageSize.getWidth();
  const pageH = pdf.internal.pageSize.getHeight();
  const margin = 10;
  const headerH = 18;
  const usableW = pageW - margin * 2;
  const usableH = pageH - margin * 2 - headerH;

  const title = TAB_TITLES[tabId] || tabId;

  const addHeader = (pageNum: number, totalLabel?: string) => {
    pdf.setFillColor(180, 30, 30);
    pdf.rect(0, 0, pageW, headerH + margin, 'F');
    pdf.setTextColor(255, 255, 255);
    pdf.setFontSize(14);
    pdf.setFont('helvetica', 'bold');
    pdf.text(`RCM Buddy — ${title}`, margin, margin + 6);
    pdf.setFontSize(8);
    pdf.setFont('helvetica', 'normal');
    const meta = pageNum === 0
      ? `${hospitalName} · ${dateRange} · Generated ${new Date().toLocaleDateString('en-IN')}`
      : `${hospitalName} · Page ${pageNum + 1}${totalLabel || ''}`;
    pdf.text(meta, margin, margin + 12);
  };

  // Scale image to fit page width
  const scale = usableW / (imgW / 2);
  const scaledH = (imgH / 2) * scale;
  const startY = headerH + margin + 2;

  if (scaledH <= usableH) {
    addHeader(0);
    pdf.addImage(imgData, 'JPEG', margin, startY, usableW, scaledH);
  } else {
    // Multi-page: slice the canvas
    const pxPerPage = Math.floor((usableH / scale) * 2);
    let srcY = 0;
    let pageNum = 0;

    while (srcY < imgH) {
      if (pageNum > 0) pdf.addPage();
      addHeader(pageNum);

      const sliceH = Math.min(pxPerPage, imgH - srcY);
      const sliceCanvas = document.createElement('canvas');
      sliceCanvas.width = imgW;
      sliceCanvas.height = sliceH;
      const ctx = sliceCanvas.getContext('2d')!;
      ctx.drawImage(canvas, 0, srcY, imgW, sliceH, 0, 0, imgW, sliceH);

      const sliceData = sliceCanvas.toDataURL('image/jpeg', 0.95);
      const sliceScaledH = (sliceH / 2) * scale;
      pdf.addImage(sliceData, 'JPEG', margin, startY, usableW, sliceScaledH);

      srcY += pxPerPage;
      pageNum++;
    }
  }

  // Footer
  pdf.setTextColor(150, 150, 150);
  pdf.setFontSize(7);
  pdf.text('Generated by RCM Buddy · rcmbuddy.com', margin, pageH - 5);

  pdf.save(`RCM_Buddy_${title.replace(/\s+/g, '_')}_${new Date().toISOString().slice(0, 10)}.pdf`);
}
